// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ityppviqvzyrbdrjxayu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0eXBwdmlxdnp5cmJkcmp4YXl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMzU4NTUsImV4cCI6MjA2NjcxMTg1NX0.w2ubwEPMjWMblJn3Ps10HkMRMz1rbrsibJiSE45KLpI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);